[2024-03-28T17:45:17.322+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: cryptocurrency_data_pipeline.create_final_table scheduled__2024-01-16T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
