[2024-03-28T17:15:10.601+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cryptocurrency_data_pipeline.create_final_table scheduled__2024-01-04T00:00:00+00:00 [queued]>
[2024-03-28T17:15:13.318+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cryptocurrency_data_pipeline.create_final_table scheduled__2024-01-04T00:00:00+00:00 [queued]>
[2024-03-28T17:15:13.460+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-03-28T17:15:18.570+0000] {taskinstance.py:2192} INFO - Executing <Task(PostgresOperator): create_final_table> on 2024-01-04 00:00:00+00:00
[2024-03-28T17:15:19.708+0000] {standard_task_runner.py:60} INFO - Started process 377 to run task
[2024-03-28T17:15:20.464+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'cryptocurrency_data_pipeline', 'create_final_table', 'scheduled__2024-01-04T00:00:00+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/cryptocurrency_data_pipeline.py', '--cfg-path', '/tmp/tmp82hgd69u']
[2024-03-28T17:15:21.279+0000] {standard_task_runner.py:88} INFO - Job 59: Subtask create_final_table
[2024-03-28T17:15:23.961+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-28T17:15:28.171+0000] {task_command.py:423} INFO - Running <TaskInstance: cryptocurrency_data_pipeline.create_final_table scheduled__2024-01-04T00:00:00+00:00 [running]> on host de9dce8fd105
[2024-03-28T17:15:36.235+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='dom@dataengineercafe.io' AIRFLOW_CTX_DAG_OWNER='domwatcharin' AIRFLOW_CTX_DAG_ID='cryptocurrency_data_pipeline' AIRFLOW_CTX_TASK_ID='create_final_table' AIRFLOW_CTX_EXECUTION_DATE='2024-01-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-04T00:00:00+00:00'
[2024-03-28T17:15:36.353+0000] {sql.py:276} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS cryptocurrency (
                timestamp BIGINT PRIMARY KEY,
                open FLOAT,
                highest FLOAT,
                lowest FLOAT,
                closing FLOAT,
                volume FLOAT
            )
        
[2024-03-28T17:15:37.223+0000] {base.py:83} INFO - Using connection ID '***' for task execution.
[2024-03-28T17:15:37.660+0000] {base.py:83} INFO - Using connection ID '***' for task execution.
[2024-03-28T17:15:37.949+0000] {sql.py:432} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS cryptocurrency (
                timestamp BIGINT PRIMARY KEY,
                open FLOAT,
                highest FLOAT,
                lowest FLOAT,
                closing FLOAT,
                volume FLOAT
            )
        , parameters: None
[2024-03-28T17:15:38.525+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 392, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 437, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(cryptocurrency, 2200) already exists.

[2024-03-28T17:15:40.405+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=cryptocurrency_data_pipeline, task_id=create_final_table, execution_date=20240104T000000, start_date=20240328T171511, end_date=20240328T171539
[2024-03-28T17:15:44.497+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2024-03-28T17:15:44.581+0000] {configuration.py:1046} WARNING - section/key [smtp/smtp_user] not found in config
[2024-03-28T17:15:44.595+0000] {email.py:270} INFO - Email alerting: attempt 1
[2024-03-28T17:15:46.114+0000] {email.py:281} INFO - Sent an alert email to ['dom@dataengineercafe.io']
[2024-03-28T17:16:01.374+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 59 for task create_final_table (duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(cryptocurrency, 2200) already exists.
; 377)
[2024-03-28T17:16:01.869+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-28T17:16:03.986+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
